insert into eyemakeup(brand,itemName,price) values("Anastasia","Modern Renaissance Palette", 42.00);
insert into eyemakeup(brand,itemName,price) values("Too Faced","Sweet Peach", 49.00);
insert into eyemakeup(brand,itemName,price) values("Urban Decay","Naked3", 54.00);
insert into eyemakeup(brand,itemName,price) values("Urban Decay","Full Spectrum", 32.00);
insert into eyemakeup(brand,itemName,price) values("Nars","NARSissist Loaded Eyeshadow", 59.00);
insert into eyemakeup(brand,itemName,price) values("Tarte","Rainforest of the Sea", 36.00);
insert into eyemakeup(brand,itemName,price) values("Tarte","Tarteist Pro Amazonian Clay", 53.00);
insert into eyemakeup(brand,itemName,price) values("Urban Decay","Moondust Palette", 49.00);
insert into eyemakeup(brand,itemName,price) values("Buxom","White Russian on the Rocks", 40.00);
insert into eyemakeup(brand,itemName,price) values("Too Faced","White Chocolate Chip", 26.00);
insert into eyemakeup(brand,itemName,price) values("Burberry","Complete Eye Palette", 62.00);
insert into eyemakeup(brand,itemName,price) values("Kat Von D","Alchemist Holographic Palette", 32.00);
insert into eyemakeup(brand,itemName,price) values("Dior","5-Colour Eyeshadow", 62.00);

insert into facemakeup(brand,itemName,price) values("Dior","Capture Totale Dreamskin",82.00);
insert into facemakeup(brand,itemName,price) values("Guerlain","Super Aqua-Serum BB",79.00);
insert into facemakeup(brand,itemName,price) values("AmorePacific","Moisture Bound",70.00);
insert into facemakeup(brand,itemName,price) values("Giorgio Armani Beauty","Designer Lift Foundation",67.00);
insert into facemakeup(brand,itemName,price) values("Bobbi Brown","Intensive Skin Serum Foundation",63.00);
insert into facemakeup(brand,itemName,price) values("Giorgio Armani Beauty","Luminous Silk Foundation",64.00);
insert into facemakeup(brand,itemName,price) values("Koh Gen Do","Aqua Foundation",62.00);
insert into facemakeup(brand,itemName,price) values("Dior","Diorskin Airflash Spray",62.00);
insert into facemakeup(brand,itemName,price) values("Marc Jacobs Beauty","Re(marc)able Foundation",55.00);
insert into facemakeup(brand,itemName,price) values("Givenchy","TEINT Couture Cushion",50.00);
insert into facemakeup(brand,itemName,price) values("Dr. Jart+","Air Mesh",48.00);
insert into facemakeup(brand,itemName,price) values("Stila","Aqua Glow",45.00);
insert into facemakeup(brand,itemName,price) values("Shiseido","Radiant Lifting Foundation",45.00);

insert into skincare(brand,itemName,price) values("Fresh","Soy Face Cleanser",38.00);
insert into skincare(brand,itemName,price) values("Sunday Riley","Good Genes Treatment",158.00);
insert into skincare(brand,itemName,price) values("Ole Henriksen","Truth Serum",48.00);
insert into skincare(brand,itemName,price) values("Clinique","Moisture Surge",39.00);
insert into skincare(brand,itemName,price) values("Drunk Elephant","C-Firma Day Serum",80.00);
insert into skincare(brand,itemName,price) values("Fresh ","Lotus Youth Cream",45.00);
insert into skincare(brand,itemName,price) values("Tatcha","The Water Cream",68.00);
insert into skincare(brand,itemName,price) values("La Mer","The Concentrate",360.00);
insert into skincare(brand,itemName,price) values("Perricone MD","Gentle Firming Eye Cream",72.00);
insert into skincare(brand,itemName,price) values("Murad","Eye Lift",68.00);
insert into skincare(brand,itemName,price) values("Dr. Jart+","Ceramidin Cream",48.00);
insert into skincare(brand,itemName,price) values("Drunk Elephant","nightbright",28.00);
insert into skincare(brand,itemName,price) values("Caudalie","Favorites Set",39.00);
insert into skincare(brand,itemName,price) values("Tata Harper","Beautifying Face Oil",68.00);