insert into eyemakeup values("Anastasia","Modern Renaissance Palette", 42.00)
insert into eyemakeup values("Too Faced","Sweet Peach", 49.00)
insert into eyemakeup values("Urban Decay","Naked3", 54.00)
insert into eyemakeup values("Urban Decay","Full Spectrum", 32.00)
insert into eyemakeup values("Nars","NARSissist Loaded Eyeshadow", 59.00)
insert into eyemakeup values("Tarte","Rainforest of the Sea", 36.00)
insert into eyemakeup values("Tarte","Tarteist Pro Amazonian Clay", 53.00)
insert into eyemakeup values("Urban Decay","Moondust Palette", 49.00)
insert into eyemakeup values("Buxom","White Russian on the Rocks", 40.00)
insert into eyemakeup values("Too Faced","White Chocolate Chip", 26.00)
insert into eyemakeup values("Burberry","Complete Eye Palette", 62.00)
insert into eyemakeup values("Kat Von D","Alchemist Holographic Palette", 32.00)
insert into eyemakeup values("Dior","5-Colour Eyeshadow", 62.00)

insert into facemakeup values("Dior","Capture Totale Dreamskin",82.00)
insert into facemakeup values("Guerlain","Super Aqua-Serum BB",79.00)
insert into facemakeup values("AmorePacific","Moisture Bound",70.00)
insert into facemakeup values("Giorgio Armani Beauty","Designer Lift Foundation",67.00)
insert into facemakeup values("Bobbi Brown","Intensive Skin Serum Foundation",63.00)
insert into facemakeup values("Giorgio Armani Beauty","Luminous Silk Foundation",64.00)
insert into facemakeup values("Koh Gen Do","Aqua Foundation",62.00)
insert into facemakeup values("Dior","Diorskin Airflash Spray",62.00)
insert into facemakeup values("Marc Jacobs Beauty","Re(marc)able Foundation",55.00)
insert into facemakeup values("Givenchy","TEINT Couture Cushion",50.00)
insert into facemakeup values("Dr. Jart+","Air Mesh",48.00)
insert into facemakeup values("Stila","Aqua Glow",45.00)
insert into facemakeup values("Shiseido","Radiant Lifting Foundation",45.00)

insert into skincare values("Fresh","Soy Face Cleanser",38.00)
insert into skincare values("Sunday Riley","Good Genes Treatment",158.00)
insert into skincare values("Ole Henriksen","Truth Serum",48.00)
insert into skincare values("Clinique","Moisture Surge",39.00)
insert into skincare values("Drunk Elephant","C-Firma Day Serum",80.00)
insert into skincare values("Fresh ","Lotus Youth Cream",45.00)
insert into skincare values("Tatcha","The Water Cream",68.00)
insert into skincare values("La Mer","The Concentrate",360.00)
insert into skincare values("Perricone MD","Gentle Firming Eye Cream",72.00)
insert into skincare values("Murad","Eye Lift",68.00)
insert into skincare values("Dr. Jart+","Ceramidin Cream",48.00)
insert into skincare values("Drunk Elephant","nightbright",28.00)
insert into skincare values("Caudalie","Favorites Set",39.00)
insert into skincare values("Tata Harper","Beautifying Face Oil",68.00)